apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m5yoao2xc-python
  janus-idp.io/tekton: m5yoao2xc-python
  backstage.io/kubernetes-id: m5yoao2xc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m5yoao2xc-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
